create or replace table DIM_MEMBER as
select
  md5(MEMBER_ID) as MEMBER_SK,
  MEMBER_ID,
  FIRST_NAME,
  LAST_NAME,
  DATE_OF_BIRTH,
  STATUS,
  BRANCH_ID,
  STATUS in ('OPEN','GOOD_STANDING') as IS_ACTIVE,
  INGESTED_AT
from STAGING_MEMBERSHIP;
